- .angular-cli.json
- lib/src/attached-overlay-trigger.directive.ts
- package.json
- tslint.json
Also fixes a build error and enforces a 100 column limit
> chore: make lint settings more flexible

- README.md
- demo/app/demo.component.ts
- lib/src/attached-overlay-anchor.directive.ts
- lib/src/attached-overlay.component.scss
- lib/src/attached-overlay.component.ts
- lib/src/attached-overlay.errors.ts
- lib/src/attached-overlay.module.ts
- lib/src/public_api.ts
- package-lock.json
Add user guide and cleanup api to be more user friendly
> feat: update api to be more user friendly

- demo/app/demo.component.ts
- lib/src/popover-anchor.directive.ts
> refactor: rename satDisableClick -> satDisablePopoverToggle

- package-lock.json
- package.json
- tools/build.js
- tools/minify-sources.js
- Move all project dependencies to devDependencies
- Add keywords/repo/issues/homepage
- Be consistent about `utf-8` vs `utf8`
> chore: improve dist package for npm

- lib/popover/popover.component.html
- lib/popover/popover.component.ts
- tools/build.js
- tools/inline-resources.js
Fixes https://github.com/ncsu-sat/popover/issues/25
> fix: inline metadata resources for successful aot builds

- CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
- tools/build.js
- tools/utils/rx-spawn.js
- tools/watch.js
Ugh. It's nasty but it works. Will revisit after unit tests are in place.
This is a retry of #38.
> chore: add some baseline file watching for tests 

- src/lib/popover/popover-anchor.directive.ts
- src/lib/popover/popover.component.ts
- src/lib/popover/popover.spec.ts
> chore: add unit test for basic behavior

- CHANGELOG.md
- package-lock.json
- package.json
> As a note, this will stay in beta until CDK is stable.
> chore: bump version to beta.0

- README.md
> docs: add note about new custom transitions api

- src/demo/app/action-api/action-api.component.scss
- src/demo/app/action-api/action-api.component.ts
- src/demo/app/demo.component.scss
- src/demo/app/demo.component.ts
- src/demo/app/demo.module.ts
- src/demo/app/focus/focus.component.scss
- src/demo/app/focus/focus.component.ts
- src/demo/app/positioning/positioning.component.scss
- src/demo/app/positioning/positioning.component.ts
- src/demo/app/select-trigger/select-trigger.component.scss
- src/demo/app/select-trigger/select-trigger.component.ts
- src/demo/app/tooltip/tooltip.component.scss
- src/demo/app/tooltip/tooltip.component.ts
- src/demo/app/transitions/transitions.component.scss
- src/demo/app/transitions/transitions.component.ts
This helps manage distinct behaviors and styles for the growing number of demos
> demo: refactor each distinct demo into a separate component

- README.md
In case you haven't fixed it  locally yet:
> docs(README): Fix wrong import

- README.md
Fixes https://github.com/ncsu-sat/popover/issues/56
> docs: add note about cdkScrollable

- src/lib/popover/popover.component.ts
- src/lib/popover/popover.spec.ts
Fixes bug illuminated in https://github.com/ncstate-sat/popover/pull/73
> fix: allow popover to exist without anchor until action method is called

- README.md
- src/demo/app/transitions/transitions.component.scss
- src/demo/app/transitions/transitions.component.ts
- src/lib/popover/popover.component.ts
- src/lib/popover/popover.spec.ts
Fixes https://github.com/ncstate-sat/popover/issues/15
> feat: add afterOpen and afterClose outputs to popover

- src/demo/app/demo.component.ts
- src/demo/app/demo.module.ts
- src/demo/app/speed-dial/speed-dial.component.scss
- src/demo/app/speed-dial/speed-dial.component.ts
- src/lib/popover/popover-anchor.directive.ts
Fixes #81 
Also adds speed dial to demo app
> fix: update transform classes on every position change

- karma.conf.js
- src/lib/popover/popover-anchor.directive.ts
- src/lib/popover/popover.component.html
- src/lib/popover/popover.component.ts
- tools/utils/rollup-globals.js
This also fixes a testing regression where autowatched tests wouldn't update.
Prereq for https://github.com/ncstate-sat/popover/issues/19
> refactor: use overlay keydown event stream for escape behavior

- README.md
- src/lib/popover/popover-anchor.directive.ts
- src/lib/popover/popover.component.ts
- src/lib/popover/popover.spec.ts
- tools/utils/rollup-globals.js
Prereq for https://github.com/ncstate-sat/popover/issues/19
> feat: expose backdrop clicks and overlay keydown events

- README.md
- src/lib/popover/popover.component.ts
- src/lib/popover/popover.spec.ts
> feat: allow auto focusing of popover to be disabled

- src/demo/app/demo.component.scss
- src/demo/app/demo.component.ts
- src/demo/app/demo.module.ts
- src/lib/popover/popover.module.ts
> fix: make popover react to directionality other than on body

- karma.conf.js
Runs with --no-sandbox on Travis
> build: fix chrome failures on travis

- src/lib/popover/popover-anchoring.service.ts
- src/lib/popover/popover.spec.ts
- This uses the same logic the ConnectedPositionStrategy did internally and should not break or change behavior at all
- Fixes #112
> refactor: use flexible position strategy internally

- package.json
- src/demo/polyfills.ts
- tools/constants.ts
- tools/prepare-package.ts
- also add 'popper' to npm keywords
> fix: copy readme to dist so it shows up on npm

- README.md
- src/demo/app/tooltip/tooltip.component.scss
- src/demo/app/tooltip/tooltip.component.ts
- src/lib/popover/popover-anchoring.service.ts
- src/lib/popover/popover-hover.directive.ts
- src/lib/popover/popover.module.ts
- src/lib/popover/popover.spec.ts
- src/lib/public_api.ts
> feat: add SatPopoverHoverDirective to for easy opt-in hover behavior

- tslint.json
> fix: tslint.json

- src/demo/app/anchor-reuse/anchor-reuse.component.ts
- src/lib/popover/popover.errors.ts
Demo for Angular 8 was not touched previously. When following publishing instructions, demo was broken due to angular 8 changes.
Now, see https://github.com/ncstate-sat/popover/wiki/releases
> fix: demo for angular 8

- README.md
> chore: updated stackblitz

- CHANGELOG.md
- CONTRIBUTING.md
- RELEASES.md
- package-lock.json
- package.json
- tools/release.ts
> chore: version to 5.0.0

- README.md
- src/lib/popover/popover-anchoring.service.ts
- src/lib/popover/popover.component.ts
> Feat: add panelclass

- tools/release.ts
Extended the publish script to ask for an OTP when run, to avoid forgetting, having to delete tags and rerun.
No need for a new version here.
> chore: added otp as prompt as a reminder when publishing

- package-lock.json
> fix: package lock file
