demo/app/demo.component.ts
lib/popover/popover-anchor.directive.ts
lib/popover/popover.component.ts
tools/rollup-globals.js

Before, users would have to get a hold of the anchor to programmatically toggle the popover, but since they will already have a template ref to the popover (for attaching it to the anchor), this makes it easier to do.
Partially addresses https://github.com/ncsu-sat/popover/issues/29

feat: add open, close, toggle methods to the popover component

---

demo/app/demo.component.ts
demo/styles.scss
lib/popover/popover-anchor.directive.ts
lib/popover/popover.component.ts

Partially addresses https://github.com/ncsu-sat/popover/issues/29
By applying the `disableBackdrop` attribute to the `sat-popover`, backdrops will no longer block interaction with the page. This should enable hover support without obstructing mouseleave events.

feat: allow backdrop to be disabled or customized

---

README.md
src/demo/app/demo.component.ts
src/lib/popover/popover-anchor.directive.ts
src/lib/popover/popover.component.ts

- It is now up to the consumer to manage opening/closing/toggling behavior
- Due to `(click)="myPopover.toggle()"` and `satDisablePopoverToggle` being approx. equally verbose, and neither behavior necessarily taking precedence, it seems best to make it opt in
- It is now up to the consumer to specify when to show a backdrop
- Basically the same reasoning as the disable toggle. The goal is to make easily opt-in solutions that are flexible for a variety of needs, rather than prescribing a solution that req's several "disable apis" to support other use cases

chore: remove default toggle behave and make backdrops opt-in

---

src/demo/app/demo.component.ts
src/demo/app/demo.module.ts
src/demo/index.html
src/lib/popover/notification.service.ts
src/lib/popover/popover-anchor.directive.ts
src/lib/popover/popover.component.ts
src/lib/popover/popover.errors.ts
src/lib/popover/popover.spec.ts

- This was a regression in beta.0
- This also refactors how the popover communicates to the anchor by adding a middleman dispatcher service.
- This adds a warning when open/close/toggle methods are called on a popover with no corresponding anchor
- This adds escape/focus demo to the demo app

fix: close popover when escape key is pressed

---

package-lock.json
src/demo/app/demo.component.scss
src/demo/app/demo.component.ts
src/demo/app/demo.module.ts
src/demo/app/positioning/positioning.component.scss
src/demo/app/positioning/positioning.component.ts
src/lib/popover/notification.service.ts
src/lib/popover/popover-anchor.directive.ts
src/lib/popover/popover.component.ts
src/lib/popover/popover.errors.ts
src/lib/popover/popover.spec.ts
src/lib/public_api.ts
tslint.json

Fixes https://github.com/ncsu-sat/popover/issues/46
- Now throws an error if an invalid xPosition or yPosition is provided to the popover.
- Starts a refactor of the demo app to move the examples into their own encapsulated components.

fix: recreate overlay when target positions are changed

---

README.md
src/demo/app/demo.component.ts
src/demo/app/demo.module.ts
src/demo/app/scroll-strategies/scroll-strategies.component.scss
src/demo/app/scroll-strategies/scroll-strategies.component.ts
src/lib/popover/notification.service.ts
src/lib/popover/popover-anchor.directive.ts
src/lib/popover/popover.component.ts
src/lib/popover/popover.errors.ts
src/lib/popover/popover.spec.ts
src/lib/public_api.ts

Fixes #20 
At the moment, there seems to be something weird with the CloseScrollStrategy. I'm either using it wrong, or it isn't properly detaching. Removed from the possible options for now and tracking at https://github.com/angular/material2/issues/7922.

feat: allow changing the scroll strategy

---

src/lib/popover/popover-anchor.directive.ts
src/lib/popover/popover.spec.ts
tools/utils/rollup-globals.js

Previously, if you updated the position or scroll strategy while the popover was open, it was dispose itself and enter a weird state. This checks if the popover is open before disposing, and if so, it waits until it is detached to dispose of it.

fix: avoid disposing overlay immediately on position or strategy updates

---

src/lib/popover/popover.component.ts
tools/watch.js

- This also adds copylib to the watch pipeline
Partially fixes https://github.com/ncstate-sat/popover/issues/51. Does not handle totally invalid transitions yet.

fix: validate that input transition exists before using

---

LICENSE
package.json
src/demo/styles.scss

Going to switch the packaging format to `@ncstate/sat-popover` in a followup.

chore: update github links and license

---

README.md
src/demo/app/action-api/action-api.component.ts
src/demo/app/focus/focus.component.ts
src/demo/app/positioning/positioning.component.ts
src/demo/app/scroll-strategies/scroll-strategies.component.ts
src/demo/app/tooltip/tooltip.component.ts
src/demo/app/transitions/transitions.component.ts
src/lib/popover/popover-anchor.directive.ts
src/lib/popover/popover.component.ts
src/lib/popover/popover.spec.ts

Fixes #68 
Fixes #72
* Adds `start` and `end` to `xPosition` and `yPosition` options
* Improves the fallback iterations to progressively emanate from the target position
BREAKING CHANGES
This removes `overlapAnchor` as a positioning option.
* If before you were using `xPosition="before" overlapAnchor="true"`, you should now use, `xPosition="start"`.
* If you were using `xPosition="after" overlapAnchor="false"`, you can now just use `xPosition="after"`.

feat: add `start` and `end` as possible positions

---

README.md
src/demo/app/action-api/action-api.component.ts
src/demo/app/focus/focus.component.ts
src/demo/app/positioning/positioning.component.ts
src/demo/app/scroll-strategies/scroll-strategies.component.ts
src/demo/app/tooltip/tooltip.component.ts
src/demo/app/transitions/transitions.component.ts
src/lib/popover/popover-anchor.directive.ts
src/lib/popover/popover.component.ts
src/lib/popover/popover.errors.ts
src/lib/popover/popover.spec.ts
src/lib/public_api.ts

- Fixes https://github.com/ncstate-sat/popover/issues/70
- This also adds `xAlign` and `yAlign` as shorthand aliases
BREAKING CHANGE
* `xPosition` has been renamed to `horizontalAlign`
* `yPosition` has been renamed to `verticalAlign`
* `SatPopoverPositionX` has been renamed to `SatPopoverHorizontalAlign`
* `SatPopoverPositionY` has been renamed to `SatPopoverVerticalAlign`

chore: rename xPosition/yPosition to horizontalAlign/verticalAlign

---

CONTRIBUTING.md
karma-test-shim.js
karma.conf.js
package-lock.json
package.json
src/lib/tsconfig.spec.json
tools/build-test.js
tools/build.js
tools/utils/rx-watch.js
tools/watch-test.js
tools/watch.js

This uses separate scripts for building/watching the lib and building/watching for specs. In a not-so-elegant way, it moves the compiled spec output to a different directory after sass compilation and inlining is complete. Doing so avoids the dozens of warnings karma was throwing during the intermediate step.

build: make test running more friendly

---

src/demo/app/anchor-reuse/anchor-reuse.component.scss
src/demo/app/anchor-reuse/anchor-reuse.component.ts
src/demo/app/demo.component.ts
src/demo/app/demo.module.ts
src/lib/popover/notification.service.ts
src/lib/popover/popover-anchor.directive.ts
src/lib/popover/popover-anchoring.service.ts
src/lib/popover/popover.component.ts
src/lib/popover/popover.spec.ts

- Use helper anchoring service to offload overlay management logic from the anchor directive
- Complete notifications stream when popover is destroyed
- Unsubscribe from internal position changes subscription before resubscribing
- Add toggle to demo app that destroys all components (for checking destroy errors)
- Add demo that can toggle which of two popovers is attached to an anchor
This is in preparation of allowing popovers to be anchored to any element via a service (part of #23).

refactor: offload overlay logic from anchor directive to a service

---

README.md
src/lib/popover/popover-anchor.directive.ts
src/lib/popover/popover-anchoring.service.ts
src/lib/popover/popover.spec.ts
src/lib/public_api.ts

Note: I'm choosing not to document this change in the README since I'd prefer a cleaner api before making this a suggested solution for dynamically anchoring popovers
Fixes #124

feat: expose anchoring service

---

tools/release.ts

- this prevents accidentally trying to use old dist version for tag
- reduce empty lines in log
- add 'github release' step to release tasks

chore: build lib before tagging release

---

CHANGELOG.md
package-lock.json
package.json

Bumping version to v4.0.0 via https://github.com/ncstate-sat/popover/wiki/releases

chore: bump to 4.0.0

---

src/demo/tsconfig.app.json

Recent upgrades caused the demo build to not build.
```bash
rm -rf node_modules package-lock.json dist
npm i
npm run build
npm run build:demo
```
all good now.

fix: demo build was not building

---

README.md
src/demo/app/transitions/transitions.component.ts
src/lib/popover/popover.animations.ts
src/lib/popover/popover.component.ts

While I can see how we can't easily get issue https://github.com/ncstate-sat/popover/issues/114 resolved, I would love to be able to at least change the relevant scale values inside the AnimationTriggerMetadata.
- Tests are green
- Updated README and demo application
Currently I am setting the open and close Transition to `0ms` and using pure CSS animations on a custom popover container :/

feat: make scale values for animation customizable

---

src/lib/popover/popover-anchoring.service.ts
src/lib/popover/popover-hover.directive.ts
src/lib/popover/popover.component.ts

When using sat-popover in strict mode, you can't use the boolean inputs without passing a boolean value. 
Doing that causes an error, because basically it's equivalent of passing an empty string into a boolean input.
Angular cdk has a simple solution for that: using inputs of type BooleanInput or NumberInput, that also accept strings.

boolean inputs are now BooleanInput (number same)

---

CHANGELOG.md
package.json

I have phased out an older npm account in favor of a new one. However apparently the last release used the old one. This release has no functional changes.

chore: fix npm account for release
